### ISSUE TITLE
反编译获取任何微信小程序源码

### ISSUE THREAD

**Issue by hullis** [hullis/vue#17]
#### 一、准备材料
    1.node.js运行环境 [下载地址](https://nodejs.org/en/) 如果没有安装nodejs，请先安装一下
    2.反编译的脚本 [下载地址](https://github.com/hullis/wxApp.git)
    3.安卓模拟器（要求自带root权限）下载地址自行百度 我使用的是夜神模拟器，用来获取小程序源文件
    4.RE管理器 下载地址自行百度,到时候直接拖到模拟器中即可

#### 二、详细步骤
  1.使用安卓模拟器获取到.wxapkg文件
    a.打开安装好的安卓模拟器
        <img src="https://hullis.cn/wxApp/img/1.png"/>
    b.在模拟器中安装QQ(方便发送.wxapkg文件)、微信(获取.wxapkg文件)
    c.安装RE管理器
        <img src="https://hullis.cn/wxApp/img/2.png"/>
    d.接下来在模拟器里打开微信，然后在微信中运行你想要获取的下程序（这其实是让微信把小程序的源文件包从服务器下载到了本地了）
        在模拟器微信中运行“XXX小程序”一下后，直接切回模拟器桌面运行RE浏览器 来到目录/data/data/com.tencent.mm/MicroMsg/appbrand/pkg/就抵达了目的文件夹
        你会看到发现里面的一些.wxapkg后缀的文件，就是它们没错啦，可以根据使用的时间来判断那个是你刚才从服务器下载过来的，一般小程序的文件不会太大（一般会有2-3个文件，那个大小达到1-2M的不是，你都可以反编译出来看看），可以结合时间来判断，长按压缩所选文件,然后再将压缩好的包通过QQ发送到我的电脑，如果不进行压缩的话，是无法将这个文件通过QQ来发送的。所以QQ的这个功能可以让我们很方便的拿到源文件，而不必到电脑目录去找模拟器的文件目录。解压。这样几步简单操作，就成功拿到了小程序的源文件了

   2.使用反编译脚本解包 wxapkg
###### 安装这些包才能正确执行这些程序，为了做到这一点，首先执行`npm install`；另外如需全局安装这些包可执行以下命令:
    1.npm install esprima
    2.npm install css-tree
    3.npm install cssbeautify
    4.npm install vm2
    5.npm install uglify-es
    6.npm install js-beautify
    7.npm install escodegen

#### 三、安装好依赖之后，就是最后一步了，反编译 .wxapkg 文件
    在当前目录下输入 node wuWxapkg.js [-d] //files 就是你想要反编译的文件名 例如：我有一个需要反编译的文件 _xxxxxx.wxapkg 已经解压到了C盘根目录下,那么就输出命令 node wuWxapkg.js C:\_xxxxxx.wxapkg
    回车运行，反编译脚本就能一步将.wxapkg 文件还原为微信开发者工具能够运行的源文件，目录地址和你反编译的文件地址是一样的 然后在微信开发者工具新增项目即可打开

**Comment by hullis** [comment]
:imp:

**Comment by Cherrison** [comment]
我做了一个一键获取源码工具, 傻瓜式操作
